# Generated by Django 2.1.2 on 2018-10-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=60)),
                ('run', models.CharField(max_length=10)),
                ('nombre_completo', models.CharField(max_length=60)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.IntegerField()),
                ('vivienda', models.CharField(choices=[('CPG', 'Casa con patio grande'), ('CPP', 'Casa con patio pequeño'), ('CSP', 'Casa sin patio'), ('DEP', 'Departamento')], default='CPG', max_length=3)),
            ],
        ),
    ]
