# Generated by Django 2.1.2 on 2018-10-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default='Arica', max_length=120),
        ),
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.CharField(default='Arica y Parinacota', max_length=100),
        ),
    ]
